initial concourse demo example

diff --git a/concourse/tasks/scan.yml b/concourse/tasks/scan.yml
--- a/concourse/tasks/scan.yml
+++ b/concourse/tasks/scan.yml
@@ -15,4 +15,8 @@ run:
   - -exc
   - |
     cd ./source-files
-    exit `python -m ephemerol ./ephemerol/test/rulebase.yml ./ephemerol/test/SampleWebApp-master.zip | jq '.scan_stats.cloud_readiness_index < 98'`
+    scan_passed=`python -m ephemerol ./ephemerol/test/rulebase.yml ./ephemerol/test/SampleWebApp-master.zip | jq '.scan_stats.cloud_readiness_index > 98'`
+    if [ "$scan_passed" == "false" ]
+       echo "Source Scan Failed"
+       exit 1
+    fi
